sudo: required

services:
  - docker

before_install:
  - docker build -t yishaiz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yishaiz/react-test npm test -- --coverage

after_success:
  - docker build -t yishaiz/multi-client ./client
  - docker build -t yishaiz/multi-nginx ./nginx
  - docker build -t yishaiz/multi-server ./server
  - docker build -t yishaiz/multi-worker ./worker
  
# Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" docker.io --password-stdin 
  # - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"

# push images to docker hub

  - docker push yishaiz/multi-client
  - docker push yishaiz/multi-nginx
  - docker push yishaiz/multi-server
  - docker push yishaiz/multi-worker

# deploy to AWS

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: docker-node-redis-postgres-react
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-eu-west-1-558343010837
  bucket_path: docker-multi

