sudo: required

services:
  - docker

before_install:
  - docker build -t yishaiz/react-test -f ./client/Docckerfile.dev ./client

script:
  - docker run -e CI=true yishaiz/react-test npm test -- --coverage

after_success:
  - docker build -t yishaiz/multi-client ./client
  - docker build -t yishaiz/multi-nginx ./nginx
  - docker build -t yishaiz/multi-server ./server
  - docker build -t yishaiz/multi-worker ./worker
  
# Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  
  



# push images to docker hub

  # docker build -t yishaiz/multi-worker ./worker
 