version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:latest'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  nginx:
    restart: always
    depends_on: 
      # - dummy_api
      - api
      - client      
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'

  # dummy_api:
  #   # depends_on: 
  #   #   - postgres
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./dummy-server
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app

  api:
    depends_on: 
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
  